# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_document_pub_date_confident'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='domain',
            field=models.TextField(blank=True, default=''),
        ),
    ]
