# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_document_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
