# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20161120_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='TfIdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_kv', models.TextField(blank=True, default='null:0.00,')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Collection')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='document',
            name='score_kv',
        ),
    ]
