# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20161120_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='score_kv',
            field=models.TextField(blank=True, default='null:0.00,'),
        ),
    ]
