# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_collection_score_kv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfidf',
            name='collection',
        ),
        migrations.DeleteModel(
            name='TfIdf',
        ),
    ]
