# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20161120_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash',
            field=models.TextField(blank=True, default=''),
        ),
    ]
