# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_document_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TfIdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_kv', models.TextField(blank=True, default='null:0.00,')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
