# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_warcfile_isfetchmetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warcfile',
            old_name='isFetchMetadata',
            new_name='isInfoGet',
        ),
    ]
